version: 2

registries:
  docker-hardened:
    type: "docker-registry"
    url: "dhi.io"
    replaces-base: true
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

updates:
- package-ecosystem: "docker"
  directory: "/"
  registries:
  - "docker-hardened"
  commit-message:
    prefix: "docker"
  labels: [ 'docker' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "weekly"
  groups:
    docker-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
